### ISSUE TITLE
When switching between NavigationButtons blazor hangs

### ISSUE THREAD

**Issue by FDLrules** [ThomasBleijendaal/RapidCMS#144]
When switching slowly, everything seems to work, but when navigating faster using navigation buttons with navigation handlers, an exception is thrown and you have to reload the page.
This is the stacktrace of the exception that is raised

```
blazor.server.js:21 [2021-11-09T20:57:02.070Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at RapidCMS.UI.Components.Sections.RootSection.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2)
   at RapidCMS.UI.Components.Forms.CascadingEditContext.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by ThomasBleijendaal** [comment]
Closed for now as it is too hard to reproduce.
